{"name": "Test of failed attempt to create a courier with repeating login", "status": "failed", "statusDetails": {"message": "AssertionError: Error message contains wrong text\nassert {'code': 409,...уйте другой.'} == {'message': '...используется'}\n  \n  Differing items:\n  {'message': 'Этот логин уже используется. Попробуйте другой.'} != {'message': 'Этот логин уже используется'}\n  Left contains 1 more item:\n  {'code': 409}\n  Use -v to get more diff", "trace": "self = <tests.test_courier_creation.TestCourierCreation object at 0x0000015039E50B90>, new_courier = (<Response [201]>, ['ubzjrwwwtr', 'vdjsoupgig', 'ompztmfoiw'])\n\n    @allure.title('Test of failed attempt to create a courier with repeating login')\n    @allure.description('Negative test of the endpoint \"Создание курьера\" POST /api/v1/courier.'\n                        'Checks impossibility of creation of a courier with repeating login')\n    def test_creation_courier_with_repeating_login_failed(self, new_courier):\n        repeating_login_payload = {\n            \"login\": new_courier[1][0],\n            \"password\": new_courier[1][1]+'a',\n            \"firstName\": new_courier[1][2]\n        }\n        print(repeating_login_payload)\n        response = requests.post(f'{url}/api/v1/courier', data=repeating_login_payload)\n        assert response.status_code == 409, f'Instead of an error code 409 received code {response.status_code}'\n>       assert response.json() == {\"message\": \"Этот логин уже используется\"}, f'Error message contains wrong text'\nE       AssertionError: Error message contains wrong text\nE       assert {'code': 409,...уйте другой.'} == {'message': '...используется'}\nE         \nE         Differing items:\nE         {'message': 'Этот логин уже используется. Попробуйте другой.'} != {'message': 'Этот логин уже используется'}\nE         Left contains 1 more item:\nE         {'code': 409}\nE         Use -v to get more diff\n\ntests\\test_courier_creation.py:56: AssertionError"}, "description": "Negative test of the endpoint \"Создание курьера\" POST /api/v1/courier.Checks impossibility of creation of a courier with repeating login", "attachments": [{"name": "stdout", "source": "c574ecd2-51e0-4306-95d1-0bca95185d44-attachment.txt", "type": "text/plain"}], "start": 1717843472200, "stop": 1717843472325, "uuid": "bb89784a-2a7f-4e72-8dce-9372b33523fb", "historyId": "8ab978168c9d5e0411bb7a302e7b837f", "testCaseId": "8ab978168c9d5e0411bb7a302e7b837f", "fullName": "tests.test_courier_creation.TestCourierCreation#test_creation_courier_with_repeating_login_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_creation"}, {"name": "subSuite", "value": "TestCourierCreation"}, {"name": "host", "value": "DESKTOP-4KK18J8"}, {"name": "thread", "value": "33984-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_creation"}]}